### ISSUE TITLE
plot: Can't change background and line color

### ISSUE THREAD

**Issue by MiguelPires** [gonum/plot#473]
### What are you trying to do?
Changing the background and line color of a plot.

### What did you do?

```
graph, err := plot.New()
if err != nil {
	return err
}

line, err := plotter.NewLine(dataPoints)
if err != nil {
	return err
}

graph.HideAxes()
graph.BackgroundColor = color.RGBA{A: 0}
line.LineStyle.Color = color.RGBA{R: 0, G: 0, B: 237, A: 255}

err = plotutil.AddLines(graph, line)
if err != nil {
	return err
}

err = graph.Save(6*vg.Centimeter, vg.Centimeter, path)
if err != nil {
	return err
}
```
### What did you expect to happen?
The background to be transparent and the line color to be blue.

### What actually happened?
The image is created but the background is still white and the line color isn't blue.

### What version of Go and Gonum/plot are you using?
Go: 1.8
gonum: 5f3c436ce602d80b13f2936b6bf149515198d6a4

**Comment by sbinet** [comment]
`line` is already a `plot.Plotter`.
`plotutil.AddLines` expects at least one `plotter.XYer`, and will create a new `plot.Plotter` value from that:
- https://github.com/gonum/plot/blob/5f3c436ce602d80b13f2936b6bf149515198d6a4/plotutil/add.go#L192

so you'd just have to replace `plotutil.AddLines(...)` with: `p.Add(line)`.

**Comment by MiguelPires** [comment]
Thank you very much, that helped!
Do you know why the background isn't changing to transparent? Are there any restrictions to this? I'm saving the graph as a png which should support it

**Comment by sbinet** [comment]
not sure whether this is a `gonum/plot` issue or one with the `vg` backend for `png`...

**Comment by ctessum** [comment]
Maybe this is related? 

https://github.com/gonum/plot/blob/master/vg/vgimg/vgimg.go#L104

**Comment by sbinet** [comment]
definitely!
![out](https://user-images.githubusercontent.com/1070920/46550477-7d440880-c8d5-11e8-872f-17cdfb880401.png)

**Comment by sbinet** [comment]
fixed by https://github.com/gonum/plot/pull/486

**Comment by kaythxbye** [comment]
Hi, I just downloaded the latest state of this repo and the issue seems to be still existing.
When I specify white or black as background colors it works, however when specifying transparent it doesn't. As a minimum breaking example I have created a new test case in `plot_test.go`:

```
func TestBackgroundColor(t *testing.T) {                                           
  p, err := plot.New()                                                             
  if err != nil {                                                                  
    t.Fatalf("Error %v", err)                                                      
  }                                                                                
                                                                                   
  p.BackgroundColor = color.Transparent                                            
  err = p.Save(6 * vg.Centimeter, 1 * vg.Centimeter, "BackgroundColor.png")        
  if err != nil {                                                                  
    t.Fatalf("Error %v", err)                                                      
  }                                                                                
}
```

After executing this with `go test ./...`, the generated file has a legend and stuff and (most importantly) a white background. Can you reproduce this?

**Comment by sbinet** [comment]
this is explained there: https://github.com/gonum/plot/pull/476#discussion_r228581871

the decision at the time was that for "sophisticated/advanced" use, one shouldn't use the "convenience" API (such as `plot.Plot.Save(...)`)

you do have a point about `plot.Plot.BackgroundColor` being somewhat overlooked (at least for `vgimg` canvases...)

**Comment by kaythxbye** [comment]
Ah thanks, I totally misunderstood your comment about the alternative PR. I thought it had the same functionality than the first one. Alright, with that in mind I can work around the issue.

However it it still a bit weird that Black and White work, while Transparent doesn't.

**Comment by ctessum** [comment]
I think the issue is that there are 2 separate background colors: the background color for the canvas and the background color for the plot. They are different concepts because there can be more than one plot on a canvas, or a plot could share a canvas with things that are not plots. 

If you set the both the canvas background color and the plot background color to transparent, then you should get the result you want. 

There may be a way to simplify the API to make this easier to understand, but it's not immediately obvious to me how to do that.

**Comment by kaythxbye** [comment]
Okay, so that means before drawing any `line` I need to get the [Canvas object](https://godoc.org/gonum.org/v1/plot/vg#Canvas), set the Color and Fill() it up entirely with a transparent rectangle?

**Comment by sbinet** [comment]
No. It means you need to create the canvas with the background color you want.
I'm not behind a real keyboard but I'll show you an example as soon as I am in front of such a thing.

**Comment by sbinet** [comment]
apologies for the belated answer, but here is the example:

```go
package main

import (
	"image/color"
	"log"
	"os"

	"gonum.org/v1/plot"
	"gonum.org/v1/plot/plotter"
	"gonum.org/v1/plot/vg"
	"gonum.org/v1/plot/vg/draw"
	"gonum.org/v1/plot/vg/vgimg"
)

func main() {
	p, err := plot.New()
	if err != nil {
		log.Fatal(err)
	}

	xys := plotter.XYs{
		plotter.XY{0, 0},
		plotter.XY{1, 1},
		plotter.XY{2, 2},
	}

	p.Title.Text = "My title"
	p.BackgroundColor = color.Transparent

	lines, points, err := plotter.NewLinePoints(xys)
	if err != nil {
		log.Fatal(err)
	}
	lines.Color = color.RGBA{B: 255, A: 255}

	p.Add(lines, points)
	p.Add(plotter.NewGrid())

	c := vgimg.PngCanvas{vgimg.NewWith(
		vgimg.UseWH(10*vg.Centimeter, 5*vg.Centimeter),
		vgimg.UseBackgroundColor(color.Transparent),
	)}
	p.Draw(draw.New(c))

	f, err := os.Create("foo.png")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	_, err = c.WriteTo(f)
	if err != nil {
		log.Fatal(err)
	}

	err = f.Close()
	if err != nil {
		log.Fatal(err)
	}
}
```

and the result:
![foo](https://user-images.githubusercontent.com/1070920/53987011-fa430a80-411f-11e9-8324-3ce825167a75.png)

**Comment by kaythxbye** [comment]
@sbinet Thank you very much, this was very helpful.
